<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
<head>
<style type="text/css">
.main{
	margin: 0 auto;
	width: 800px;
	border-left:1px solid #000;
	border-right:1px solid #000;
}

.banner{
	height: 180px;
	width: 800px;
	background-image: url("img/bgimg.jpg");
	background-repeat:no-repeat;
	
	
}
.content{
	height: 400px;
	width: 800px;
	
}
.footer{
	height: 50px;
	width: 800px;
	background-color: #D6E6FD; 
	text-align: center;
	vertical-align: middle;
}

.ban1{
	height:90px;
	font-size: 36px;
	vertical-align: middle;
	text-align: center;
}
.ban2{
	height:20px;
	font-size: 18px;
	vertical-align: middle;
	text-align: center;
}
.ban3{
	height:90px;
	font-size: 18px;
	vertical-align: middle;
	text-align: center;
}
.ht{
	padding: 35px;
}
.at{
	padding: 5px;
}
.ft{
	padding: 20px;
}
</style>
<meta charset="UTF-8">
<title>Java Web应用程序开发</title>
</head>
<body>
<div class="main">
<div class="banner">
<div class="ban1"><p class="ht"><b>Java Web应用程序开发</b></p></div>
<div class="ban2">软件工程专业&nbsp2017级2班&nbsp201709090216&nbsp卢富强</div>
<hr>
<div class="ban3"><p class="at"><a href="index_202.jsp">Jsp基本操作</a>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="login_301.jsp">数据库访问</a></p></div>
</div>
